//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 05:51:04 PM GMT+01:00 
//


package ch.corner.service.conveniencecard.configuration.conveniencecardconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import ch.corner.service.conveniencecard.common.BasicResponse;


/**
 * <p>Java class for getNationListResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getNationListResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://common.conveniencecard.service.corner.ch}basicResponse">
 *       &lt;sequence>
 *         &lt;element name="nation" type="{http://configuration.conveniencecard.service.corner.ch/convenienceCardConfiguration}nation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNationListResponse", propOrder = {
    "nation"
})
public class GetNationListResponse
    extends BasicResponse
{

    protected List<Nation> nation;

    /**
     * Gets the value of the nation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nation }
     * 
     * 
     */
    public List<Nation> getNation() {
        if (nation == null) {
            nation = new ArrayList<Nation>();
        }
        return this.nation;
    }

}
