//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 01:15:52 PM GMT+01:00 
//


package ch.corner.service.conveniencecard.configuration.conveniencecardconfiguration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nationCodeIso3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nationCodeIso2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nationCodeCb" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nationI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nationD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nationF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nationE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phoneCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nation", propOrder = {
    "nationCodeIso3",
    "nationCodeIso2",
    "nationCodeCb",
    "nationI",
    "nationD",
    "nationF",
    "nationE",
    "phoneCountryCode"
})
public class Nation {

    protected String nationCodeIso3;
    protected String nationCodeIso2;
    protected String nationCodeCb;
    protected String nationI;
    protected String nationD;
    protected String nationF;
    protected String nationE;
    protected String phoneCountryCode;

    /**
     * Gets the value of the nationCodeIso3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationCodeIso3() {
        return nationCodeIso3;
    }

    /**
     * Sets the value of the nationCodeIso3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationCodeIso3(String value) {
        this.nationCodeIso3 = value;
    }

    /**
     * Gets the value of the nationCodeIso2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationCodeIso2() {
        return nationCodeIso2;
    }

    /**
     * Sets the value of the nationCodeIso2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationCodeIso2(String value) {
        this.nationCodeIso2 = value;
    }

    /**
     * Gets the value of the nationCodeCb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationCodeCb() {
        return nationCodeCb;
    }

    /**
     * Sets the value of the nationCodeCb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationCodeCb(String value) {
        this.nationCodeCb = value;
    }

    /**
     * Gets the value of the nationI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationI() {
        return nationI;
    }

    /**
     * Sets the value of the nationI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationI(String value) {
        this.nationI = value;
    }

    /**
     * Gets the value of the nationD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationD() {
        return nationD;
    }

    /**
     * Sets the value of the nationD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationD(String value) {
        this.nationD = value;
    }

    /**
     * Gets the value of the nationF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationF() {
        return nationF;
    }

    /**
     * Sets the value of the nationF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationF(String value) {
        this.nationF = value;
    }

    /**
     * Gets the value of the nationE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationE() {
        return nationE;
    }

    /**
     * Sets the value of the nationE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationE(String value) {
        this.nationE = value;
    }

    /**
     * Gets the value of the phoneCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneCountryCode() {
        return phoneCountryCode;
    }

    /**
     * Sets the value of the phoneCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneCountryCode(String value) {
        this.phoneCountryCode = value;
    }

}
