//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 05:51:04 PM GMT+01:00 
//


package ch.corner.service.conveniencecard.configuration.conveniencecardconfiguration;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paramInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paramInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfPartnerPerClient" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="numberOfCardsPerClient" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="annualReloadableAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="annualReloadableAmountCurrency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paramInfo", propOrder = {
    "partner",
    "productType",
    "numberOfPartnerPerClient",
    "numberOfCardsPerClient",
    "annualReloadableAmount",
    "annualReloadableAmountCurrency"
})
public class ParamInfo {

    protected String partner;
    protected String productType;
    protected Integer numberOfPartnerPerClient;
    protected Integer numberOfCardsPerClient;
    protected BigDecimal annualReloadableAmount;
    protected String annualReloadableAmountCurrency;

    /**
     * Gets the value of the partner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartner() {
        return partner;
    }

    /**
     * Sets the value of the partner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartner(String value) {
        this.partner = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the numberOfPartnerPerClient property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfPartnerPerClient() {
        return numberOfPartnerPerClient;
    }

    /**
     * Sets the value of the numberOfPartnerPerClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfPartnerPerClient(Integer value) {
        this.numberOfPartnerPerClient = value;
    }

    /**
     * Gets the value of the numberOfCardsPerClient property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfCardsPerClient() {
        return numberOfCardsPerClient;
    }

    /**
     * Sets the value of the numberOfCardsPerClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfCardsPerClient(Integer value) {
        this.numberOfCardsPerClient = value;
    }

    /**
     * Gets the value of the annualReloadableAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAnnualReloadableAmount() {
        return annualReloadableAmount;
    }

    /**
     * Sets the value of the annualReloadableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAnnualReloadableAmount(BigDecimal value) {
        this.annualReloadableAmount = value;
    }

    /**
     * Gets the value of the annualReloadableAmountCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnualReloadableAmountCurrency() {
        return annualReloadableAmountCurrency;
    }

    /**
     * Sets the value of the annualReloadableAmountCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnualReloadableAmountCurrency(String value) {
        this.annualReloadableAmountCurrency = value;
    }

}
