//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 01:15:52 PM GMT+01:00 
//


package com.shifthunter.conveniencecardconfigurationmock;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tNapAndCity" type="{http://www.shifthunter.com/convenienceCardConfigurationMock}tNapAndCity"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tNapAndCity"
})
@XmlRootElement(name = "GetNapAndCityResponse")
public class GetNapAndCityResponse {

    @XmlElement(required = true)
    protected TNapAndCity tNapAndCity;

    /**
     * Gets the value of the tNapAndCity property.
     * 
     * @return
     *     possible object is
     *     {@link TNapAndCity }
     *     
     */
    public TNapAndCity getTNapAndCity() {
        return tNapAndCity;
    }

    /**
     * Sets the value of the tNapAndCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNapAndCity }
     *     
     */
    public void setTNapAndCity(TNapAndCity value) {
        this.tNapAndCity = value;
    }

}
