//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 01:35:30 PM GMT+01:00 
//


package ch.corner.service.conveniencecard.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import ch.corner.service.conveniencecard.common.BasicResponse;


/**
 * <p>Java class for getParamInfoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getParamInfoResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://common.conveniencecard.service.corner.ch}basicResponse">
 *       &lt;sequence>
 *         &lt;element name="paramInfo" type="{http://configuration.conveniencecard.service.corner.ch}paramInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getParamInfoResponse", propOrder = {
    "paramInfo"
})
public class GetParamInfoResponse
    extends BasicResponse
{

    protected List<ParamInfo> paramInfo;

    /**
     * Gets the value of the paramInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paramInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParamInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamInfo }
     * 
     * 
     */
    public List<ParamInfo> getParamInfo() {
        if (paramInfo == null) {
            paramInfo = new ArrayList<ParamInfo>();
        }
        return this.paramInfo;
    }

}
