//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.15 at 10:56:31 AM GMT+01:00 
//


package ch.corner.service.conveniencecard.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pf20Element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pf20Element">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="keyElement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="decodeElement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pf20Element", propOrder = {
    "keyElement",
    "decodeElement"
})
public class Pf20Element {

    protected String keyElement;
    protected String decodeElement;

    /**
     * Gets the value of the keyElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyElement() {
        return keyElement;
    }

    /**
     * Sets the value of the keyElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyElement(String value) {
        this.keyElement = value;
    }

    /**
     * Gets the value of the decodeElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecodeElement() {
        return decodeElement;
    }

    /**
     * Sets the value of the decodeElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecodeElement(String value) {
        this.decodeElement = value;
    }

}
